version: "3"

services:
  
  jupyter:
    container_name: "tl_jupyter"
    image: jupyter/scipy-notebook
    ports:
      - 8888:8888
  
  superset:
    container_name: "tl_superset"
    image: tylerfowler/superset
    ports:
      - 8088:8088
  
  postgres:
    container_name: "tl_postgres"
    image: postgres
    volumes:
      - pg_volume:/var/lib/postgresql/
    ports:
      - 5432:5432

  minio:
    container_name: "tl_minio"
    image: minio
    volumes:
      - minio_volume:/data
    ports:
      - 9000:9000
    command:
      - server /data

  apistar:
    container_name: "tl_apistar"
    build: services/apistar
    volumes:
      - ./services/apistar/api:/usr/src/app
    ports:
      - 8000:8000
    command:
      - gunicorn app:app -b 0.0.0.0:8000

  volumes:
    pg_volume
    minio_volume