version: "3"

services:
  
  jupyter:
    container_name: "tl_jupyter"
    image: jupyter/scipy-notebook
    ports:
      - 8888:8888
  
  superset:
    container_name: "tl_superset"
    image: tylerfowler/superset
    ports:
      - 8088:8088
  
  postgres:
    container_name: "tl_postgres"
    image: postgres
    volumes:
      - pg_volume:/var/lib/postgresql/
    ports:
      - 5432:5432

  volumes:
    pg_volume